#!/usr/bin/python3
def raise_exception_msg(name):
    return (print(name))
